const strainDB = {
 'OG' : 'OG Ps cubexsis'
,'B+' : '(original genetics)'
,'PE' : '<p>(original genetics),</p><p>probably by Pollock + McKenna from amazonian/colombian stock</p>'
,'Melmak' : 'iso of PE'
,'TW' : 'Tidal Wave: B+ x PE'
,'KSSS' : 'Koh Samui Super Strain, original genetics'
,'GT' : 'Golden Teacher, original genetics'
,'GT_subgroup' : 'Golden Teacher, original genetics'
,'Yimir' : 'info?'
,'Mr_Krinkle' : 'derivative? isolation? strain? info?'
,'Choco_Krinkle' : 'Choco Krinkle: Mr. Krinkle x El Choco'
,'CK_Brains' : 'CK Brains: Mr. Krinkle x El Choco'
,'Leng' : 'info?'
,'Ground_Zero' : 'Ground Zero: Leng x Choda"'
,'Wombat_TAT' : 'info?'
,'Jack_Frost' : 'Jack Frost: (W)TAT x APE'
,'Albino_KSAT' : 'Albino KSAT: TAT x KSSS'
,'Golden_KSAT' : 'Golden KSAT: TAT x KSSS'
,'TAT' : 'OG TAT: True Albino Teacher<p>GT Mutation</p>'
,'TAT_subgroup' : 'OG TAT: True Albino Teacher<p>GT Mutation</p>'
,'Toad' : 'info?'
,'RR' : 'RogerRabbits: Leucistic TAT'
,'Yeti' : 'info?'
,'Nutcracker' : 'info?'
,'Yeti2' : 'info?'
,'Deep_End' : 'info?'
,'Clockwerk_TAT' : 'info?'
,'Colckwerk_Orange' : 'info? revert?'
,'NST' : 'info?'
,'Ghost' : 'info?'
,'TAT_Black_Cap' : 'info?'
,'Harlequin' : 'info?'
,'Toad_Black_Cap' : 'Toad Black Cap: Toad x TAT Black Cap'
,'Riptide' : 'Riptide: TAT x TW'
,'A_Riptide' : '? Albino Riptide'
,'TAM' : 'TAM: <p>TAM project: TAT x Melmak</p>'
,'TAM_subgroup' : 'TAM: <p>TAM project: TAT x Melmak</p>'
,'XXX' : 'info?'
,'Pearly_Gates' : 'info?'
,'Gandalf' : 'Gandalf: developed by MycoMama Angela and Bjorn <p>It is a "pass it along for free" strain. It is to NEVER be sold. Only gifted</p><p>Gandalf finds you</p>'
,'Eye_Like' : 'info?'
,'MVP' : 'info?'
,'AMVP' : 'info? Albino MVP?'
,'End_Game' : 'info?'
,'Blue_Moon' : 'info?'
,'TePe' : '(name origin?): Tidalwave x PE'
//template:
//no spaces in first element! 
// use <p> and </p> for line breaks
//,'NewStrain' : 'NewStrain: <p>found by __, strainA x strainB</p>'
};
