const strainDB = {
'OG' : 'OG Ps cubexsis',
'B+' : '(original genetics)',
'PE' : '(original genetics), <p>probably by Pollock + McKenna from amazonian/colombian stock</p>',
'Melmak' : 'iso of PE',
'TW' : 'Tidal Wave: B+ x PE',
'KSSS' : 'Koh Samui Super Strain, original genetics',
'GT' : 'Golden Teacher, original genetics',
'GT_subgroup' : 'Golden Teacher, original genetics',
'Yimir' : 'info?',
'Mr_Krinkle' : 'derivative? isolation? strain? info?',
'Choco_Krinkle' : 'Choco Krinkle: Mr. Krinkle x El Choco',
'CK_Brains' : 'CK Brains: Mr. Krinkle x El Choco',
'Leng' : 'info?',
'Ground_Zero' : 'Ground Zero: Leng x Choda"',
'Wombat_TAT' : 'info?',
'Jack_Frost' : 'Jack Frost: (W)TAT x APE',
'Albino_KSAT' : 'Albino KSAT: TAT x KSSS',
'Golden_KSAT' : 'Golden KSAT: TAT x KSSS',
'OG_TAT' : 'OG TAT: True Albino Teacher<p>GT Mutation</p>',
'OG_TAT_subgroup' : 'OG TAT: True Albino Teacher<p>GT Mutation</p>',
'Toad' : 'info?',
'RR' : 'RogerRabbits: Leucistic TAT',
'Yeti' : 'info?',
'Nutcracker' : 'info?',
'Yeti2' : 'info?',
'Deep_End' : 'info?',
'Clockwerk_TAT' : 'info?',
'Colckwerk_Orange' : 'info? revert?',
'NST' : 'info?',
'Ghost' : 'info?',
'TAT_Black_Cap' : 'info?',
'Harlequin' : 'info?',
'Toad_Black_Cap' : 'Toad Black Cap: Toad x TAT Black Cap',
'Riptide' : 'Riptide: TAT x TW',
'A_Riptide' : '? Albino Riptide',
'TAM' : 'TAM project: TAT x Melmak"',
'XXX' : 'info?',
'Pearly_Gates' : 'info?',
'Gandalf' : 'info? Gandalf finds you',
'Eye_Like' : 'info?',
'MVP' : 'info?',
'AMVP' : 'info? Albino MVP?',
'End_Game' : 'info?',
'Blue_Moon' : 'info?'
};